Add F.cascade to ResultsCount
smartprocure/contexture-react pull request #448
Opened 2020-10-21 04:47 UTC by Akrion

- With memory provider, the context does not have `response` which breaks the `ResultsCount` component

2020-10-21 04:49 UTC, decrapifier commented
<!--
  0 failure: 
  1 warning:  The README has no...
  2 messages
  1 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 677fd5ae861bf43dbc5bfd1471906a9738a18410


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 228180275ad48a5a63ea21f9a23ee449071deba4
</p>

2020-10-21 12:07 UTC, dshishkov approved these changes

2020-10-21 23:16 UTC, daedalus28 approved these changes

2020-10-21 23:17 UTC, daedalus28 requested changes

2020-10-21 23:17 UTC, daedalus28 commented on src/exampleTypes/ResultCount.js
>    return count ? display(node.context.response.totalRecords) : 'No Results'
shouldn't this also cascade for totalRecords?

2020-10-22 00:48 UTC, daedalus28 approved these changes

2020-10-22 00:48 UTC, merged