feat: allow ability to filter out joinOptions in the TagsJoinPicker and TagsQuerySearchBar
smartprocure/contexture-react pull request #479
Opened 2021-03-15 21:36 UTC by ccalbaugh

You can now filter down the ['none', 'all', 'any'] options TagsJoinPicker by passing an explicit array of options.  

EX: `joinOptions: ['all', 'any']`
Or in TagsQuerySearchBar it would be `tagsQueryProps={{ joinOptions: ['any', 'all'] }}`

2021-03-15 21:37 UTC, decrapifier commented
<!--
  0 failure: 
  2 warning:  Branch being merg..., The README has no...
  1 messages
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1b7da6b02b91767349948adaf01cdbcf26b85f57
</p>

2021-03-18 13:11 UTC, stellarhoof requested changes

2021-03-18 13:11 UTC, stellarhoof commented on src/exampleTypes/TagsJoinPicker.js
> +    : defaultJoinOptions
`_.intersectionWith((left, right) => left.value === right, defaultJoinOptions)` ;)

2021-03-18 15:36 UTC, daedalus28 commented on src/exampleTypes/TagsJoinPicker.js
> +    : defaultJoinOptions
Nice ⛳

2021-03-18 17:33 UTC, ccalbaugh commented on src/exampleTypes/TagsJoinPicker.js
> +    : defaultJoinOptions
<img src=https://media.giphy.com/media/7Mj3OdEic7QyI/giphy.gif/>

2021-03-18 17:41 UTC, stellarhoof approved these changes

2021-03-19 16:44 UTC, merged