add loader to TagsQuery component
smartprocure/contexture-react pull request #493
Opened 2021-04-20 18:02 UTC by vstlouis

This adds loading to the TagsQuery component. I also added them to storybook.

2021-04-20 18:03 UTC, vstlouis commented
I think we should disable the popover if it is loading (not being able to trigger it via a click if the node is updating), thoughts @stellarhoof @daedalus28

2021-04-20 18:03 UTC, decrapifier commented
<!--
  2 failure:  The version was n..., The changelog has...
  2 warning:  The README has no..., Branch being merg...
  1 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against da449a3b55c951af05b2124b443560939f7b45b5
</p>

2021-04-21 15:48 UTC, stellarhoof commented
That blue on green looks ugghh

2021-06-01 19:12 UTC, daedalus28 requested changes
RE: @stellarhoof's comment - we already have the ability to customize it per component, so we can just make a generic color loader that gets injected for TagQuery specifically.

2021-06-01 19:12 UTC, daedalus28 commented on src/exampleTypes/TagsQuery/index.js
> +                {props.value}(
we should add a space before the parens like the above

2021-06-01 19:12 UTC, daedalus28 commented on src/exampleTypes/TagsQuery/index.js
> +  Loader = Loader || ThemeLoader || StripedLoader
these shouldn't be necessary - the contexture react theme API allows you to override the theme components, so we should just use that

2021-06-29 19:21 UTC, daedalus28 commented
This is stale and no longer relevant

2021-06-29 19:21 UTC, closed without merging