Bulk filter/column add feature
smartprocure/contexture-react pull request #514
Opened 2021-08-10 02:14 UTC by Akrion

- Adds bulk add support to the NestedPicker
- UI tweaks on the associated components to make them more usable

<img width="586" alt="CleanShot 2021-08-09 at 21 12 57@2x" src="https://user-images.githubusercontent.com/910303/128798041-de62d586-a147-49d9-8c21-e4a9ec894d1e.png">

<img width="567" alt="CleanShot 2021-08-09 at 21 13 39@2x" src="https://user-images.githubusercontent.com/910303/128798109-67db094e-9647-4393-9ee8-adf8ba933b50.png">

2021-08-10 02:16 UTC, decrapifier commented
<!--
  2 failure:  The version was n..., The changelog has...
  1 warning:  The README has no...
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 2848cae0f0cb79de58d6558aa057c984efe26929


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6ec4f6cfd3648ed1a85d30dfc279b5f577e87205
</p>

2021-08-12 20:04 UTC, stellarhoof requested changes

2021-08-12 20:07 UTC, Akrion commented on src/greyVest/NestedPicker.js
> +  let state = observable({
Did you try it? Use the storybook ...

2021-08-12 20:16 UTC, stellarhoof commented on src/greyVest/NestedPicker.js
> +  let state = observable({
I'm doing that now and it works but that's not the point. This pattern is just very fragile. The component will break on a rerender. That's why there's a hook provided by mobx-react that uses internal state so you always get the same observable store.

2021-08-12 21:51 UTC, Akrion commented on src/greyVest/NestedPicker.js
> +  let state = observable({
Which hook is that? https://github.com/mobxjs/mobx-react#uselocalobservable-hook?

2021-08-12 21:58 UTC, stellarhoof commented on src/greyVest/NestedPicker.js
> +  let state = observable({
`useLocalObservable`: https://mobx.js.org/react-integration.html#using-local-observable-state-in-observer-components

2021-08-12 22:21 UTC, Akrion commented on src/greyVest/NestedPicker.js
> +  let state = observable({
```
WARNING in ./src/greyVest/NestedPicker.js 176:14-32 "export 'useLocalObservable' was not found in 'mobx-react'
```

2021-08-13 13:46 UTC, stellarhoof commented on src/greyVest/NestedPicker.js
> +  let state = observable({
It's either in mobx-react-lite or we have to bump mobx-react

2021-08-13 20:56 UTC, stellarhoof approved these changes
This is such a nice improvement on the picker :)

2021-08-16 14:53 UTC, ccalbaugh commented on src/greyVest/NestedPicker.stories.js
> +    <NestedPicker options={options} onChange={x => action(`picked`)(x)} />
Is there a reason the onChange got wrapped with the extra function?  It doesn't seem necessary

2021-08-16 15:06 UTC, merged